deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    ready_wait: 120
    depends_on:
      - CMS_SERVER:
            app: child-deployment
            envs:
              - TEST_VAL=42
              - CLIENT_API_ID=7612
